create table automoviles (
	id INT,
	marca VARCHAR(50),
	modelo VARCHAR(50),
	anio_modelo VARCHAR(50)
);
insert into automoviles (id, marca, modelo, anio_modelo) values (1, 'Nissan', 'Xterra', 2012);
insert into automoviles (id, marca, modelo, anio_modelo) values (2, 'Mitsubishi', 'Cordia', 1987);
insert into automoviles (id, marca, modelo, anio_modelo) values (3, 'Dodge', 'Ram Van 1500', 1996);
insert into automoviles (id, marca, modelo, anio_modelo) values (4, 'Acura', 'RSX', 2002);
insert into automoviles (id, marca, modelo, anio_modelo) values (5, 'Audi', 'A7', 2012);
insert into automoviles (id, marca, modelo, anio_modelo) values (6, 'Ford', 'Festiva', 1991);
insert into automoviles (id, marca, modelo, anio_modelo) values (7, 'Chevrolet', 'Cobalt', 2008);
insert into automoviles (id, marca, modelo, anio_modelo) values (8, 'Pontiac', 'Trans Sport', 1994);
insert into automoviles (id, marca, modelo, anio_modelo) values (9, 'Volvo', 'S40', 2003);
insert into automoviles (id, marca, modelo, anio_modelo) values (10, 'Mitsubishi', 'RVR', 1995);
insert into automoviles (id, marca, modelo, anio_modelo) values (11, 'Volkswagen', 'Passat', 1993);
insert into automoviles (id, marca, modelo, anio_modelo) values (12, 'Dodge', 'Stratus', 2006);
insert into automoviles (id, marca, modelo, anio_modelo) values (13, 'Kia', 'Rondo', 2010);
insert into automoviles (id, marca, modelo, anio_modelo) values (14, 'Nissan', 'Quest', 2008);
insert into automoviles (id, marca, modelo, anio_modelo) values (15, 'Lincoln', 'Continental', 1993);
insert into automoviles (id, marca, modelo, anio_modelo) values (16, 'Bentley', 'Azure', 2009);
insert into automoviles (id, marca, modelo, anio_modelo) values (17, 'Jaguar', 'XJ', 2012);
insert into automoviles (id, marca, modelo, anio_modelo) values (18, 'Chevrolet', 'Express 2500', 2003);
insert into automoviles (id, marca, modelo, anio_modelo) values (19, 'Volkswagen', 'Type 2', 1988);
insert into automoviles (id, marca, modelo, anio_modelo) values (20, 'Dodge', 'Viper', 1992);
insert into automoviles (id, marca, modelo, anio_modelo) values (21, 'Chevrolet', 'Silverado 2500', 2001);
insert into automoviles (id, marca, modelo, anio_modelo) values (22, 'Toyota', 'Camry', 2011);
insert into automoviles (id, marca, modelo, anio_modelo) values (23, 'Mercedes-Benz', 'SL-Class', 1986);
insert into automoviles (id, marca, modelo, anio_modelo) values (24, 'Mazda', 'Familia', 1992);
insert into automoviles (id, marca, modelo, anio_modelo) values (25, 'Porsche', '911', 1989);
insert into automoviles (id, marca, modelo, anio_modelo) values (26, 'Toyota', 'Land Cruiser', 2004);
insert into automoviles (id, marca, modelo, anio_modelo) values (27, 'Toyota', 'Corolla', 1996);
insert into automoviles (id, marca, modelo, anio_modelo) values (28, 'BMW', '3 Series', 1997);
insert into automoviles (id, marca, modelo, anio_modelo) values (29, 'GMC', 'Jimmy', 1998);
insert into automoviles (id, marca, modelo, anio_modelo) values (30, 'Land Rover', 'Freelander', 2008);
insert into automoviles (id, marca, modelo, anio_modelo) values (31, 'Mitsubishi', 'Outlander', 2012);
insert into automoviles (id, marca, modelo, anio_modelo) values (32, 'Chevrolet', 'Avalanche 1500', 2006);
insert into automoviles (id, marca, modelo, anio_modelo) values (33, 'Infiniti', 'M', 2003);
insert into automoviles (id, marca, modelo, anio_modelo) values (34, 'Porsche', 'Cayenne', 2005);
insert into automoviles (id, marca, modelo, anio_modelo) values (35, 'Land Rover', 'Freelander', 2008);
insert into automoviles (id, marca, modelo, anio_modelo) values (36, 'Chevrolet', 'G-Series G10', 1992);
insert into automoviles (id, marca, modelo, anio_modelo) values (37, 'Ford', 'Five Hundred', 2007);
insert into automoviles (id, marca, modelo, anio_modelo) values (38, 'Mitsubishi', 'Endeavor', 2005);
insert into automoviles (id, marca, modelo, anio_modelo) values (39, 'Toyota', 'Corolla', 1995);
insert into automoviles (id, marca, modelo, anio_modelo) values (40, 'Honda', 'Pilot', 2009);
insert into automoviles (id, marca, modelo, anio_modelo) values (41, 'Mazda', 'Millenia', 1997);
insert into automoviles (id, marca, modelo, anio_modelo) values (42, 'Infiniti', 'M', 2007);
insert into automoviles (id, marca, modelo, anio_modelo) values (43, 'Honda', 'Odyssey', 2004);
insert into automoviles (id, marca, modelo, anio_modelo) values (44, 'Acura', 'RL', 2001);
insert into automoviles (id, marca, modelo, anio_modelo) values (45, 'Nissan', 'Maxima', 2003);
insert into automoviles (id, marca, modelo, anio_modelo) values (46, 'Lincoln', 'Continental Mark VII', 1986);
insert into automoviles (id, marca, modelo, anio_modelo) values (47, 'Lexus', 'ES', 2011);
insert into automoviles (id, marca, modelo, anio_modelo) values (48, 'Volkswagen', 'Passat', 1994);
insert into automoviles (id, marca, modelo, anio_modelo) values (49, 'Ford', 'LTD', 1985);
insert into automoviles (id, marca, modelo, anio_modelo) values (50, 'Pontiac', 'Vibe', 2008);
insert into automoviles (id, marca, modelo, anio_modelo) values (51, 'Nissan', 'Sentra', 2006);
insert into automoviles (id, marca, modelo, anio_modelo) values (52, 'BMW', 'X5', 2006);
insert into automoviles (id, marca, modelo, anio_modelo) values (53, 'Bentley', 'Continental Flying Spur', 2010);
insert into automoviles (id, marca, modelo, anio_modelo) values (54, 'Nissan', 'Frontier', 2005);
insert into automoviles (id, marca, modelo, anio_modelo) values (55, 'Honda', 'Passport', 1995);
insert into automoviles (id, marca, modelo, anio_modelo) values (56, 'Cadillac', 'XLR', 2006);
insert into automoviles (id, marca, modelo, anio_modelo) values (57, 'Toyota', 'Avalon', 1996);
insert into automoviles (id, marca, modelo, anio_modelo) values (58, 'Mercedes-Benz', 'GL-Class', 2010);
insert into automoviles (id, marca, modelo, anio_modelo) values (59, 'Nissan', 'Versa', 2012);
insert into automoviles (id, marca, modelo, anio_modelo) values (60, 'Scion', 'tC', 2008);
insert into automoviles (id, marca, modelo, anio_modelo) values (61, 'Dodge', 'Avenger', 2012);
insert into automoviles (id, marca, modelo, anio_modelo) values (62, 'Dodge', 'Ram 1500', 1996);
insert into automoviles (id, marca, modelo, anio_modelo) values (63, 'Buick', 'Electra', 1987);
insert into automoviles (id, marca, modelo, anio_modelo) values (64, 'Mazda', 'MX-5', 2006);
insert into automoviles (id, marca, modelo, anio_modelo) values (65, 'Hyundai', 'XG350', 2002);
insert into automoviles (id, marca, modelo, anio_modelo) values (66, 'Nissan', 'Maxima', 1994);
insert into automoviles (id, marca, modelo, anio_modelo) values (67, 'Toyota', 'Sienna', 2007);
insert into automoviles (id, marca, modelo, anio_modelo) values (68, 'Subaru', 'Impreza', 2007);
insert into automoviles (id, marca, modelo, anio_modelo) values (69, 'Mercedes-Benz', 'SL-Class', 1987);
insert into automoviles (id, marca, modelo, anio_modelo) values (70, 'Infiniti', 'J', 1997);
insert into automoviles (id, marca, modelo, anio_modelo) values (71, 'Chevrolet', 'Colorado', 2009);
insert into automoviles (id, marca, modelo, anio_modelo) values (72, 'Audi', '4000s Quattro', 1986);
insert into automoviles (id, marca, modelo, anio_modelo) values (73, 'Nissan', 'Cube', 2012);
insert into automoviles (id, marca, modelo, anio_modelo) values (74, 'Mercedes-Benz', 'GLK-Class', 2010);
insert into automoviles (id, marca, modelo, anio_modelo) values (75, 'Land Rover', 'Range Rover', 2001);
insert into automoviles (id, marca, modelo, anio_modelo) values (76, 'Volkswagen', 'Eurovan', 2001);
insert into automoviles (id, marca, modelo, anio_modelo) values (77, 'Ford', 'Mustang', 1969);
insert into automoviles (id, marca, modelo, anio_modelo) values (78, 'Buick', 'Rendezvous', 2005);
insert into automoviles (id, marca, modelo, anio_modelo) values (79, 'Toyota', 'FJ Cruiser', 2011);
insert into automoviles (id, marca, modelo, anio_modelo) values (80, 'Oldsmobile', 'Alero', 2003);
insert into automoviles (id, marca, modelo, anio_modelo) values (81, 'Nissan', 'Pathfinder', 2012);
insert into automoviles (id, marca, modelo, anio_modelo) values (82, 'GMC', 'Suburban 2500', 1996);
insert into automoviles (id, marca, modelo, anio_modelo) values (83, 'Mazda', 'B-Series', 2005);
insert into automoviles (id, marca, modelo, anio_modelo) values (84, 'Infiniti', 'I', 1998);
insert into automoviles (id, marca, modelo, anio_modelo) values (85, 'Toyota', 'Xtra', 1995);
insert into automoviles (id, marca, modelo, anio_modelo) values (86, 'Hummer', 'H1', 1999);
insert into automoviles (id, marca, modelo, anio_modelo) values (87, 'Audi', 'A3', 2009);
insert into automoviles (id, marca, modelo, anio_modelo) values (88, 'Land Rover', 'Range Rover', 2010);
insert into automoviles (id, marca, modelo, anio_modelo) values (89, 'Chrysler', '300M', 2004);
insert into automoviles (id, marca, modelo, anio_modelo) values (90, 'Mazda', 'Protege', 1994);
insert into automoviles (id, marca, modelo, anio_modelo) values (91, 'Toyota', 'Camry Solara', 2007);
insert into automoviles (id, marca, modelo, anio_modelo) values (92, 'Mazda', 'CX-9', 2009);
insert into automoviles (id, marca, modelo, anio_modelo) values (93, 'Jaguar', 'XJ Series', 1998);
insert into automoviles (id, marca, modelo, anio_modelo) values (94, 'Hyundai', 'Sonata', 1993);
insert into automoviles (id, marca, modelo, anio_modelo) values (95, 'Chevrolet', 'Avalanche', 2006);
insert into automoviles (id, marca, modelo, anio_modelo) values (96, 'GMC', 'Sonoma Club Coupe', 1995);
insert into automoviles (id, marca, modelo, anio_modelo) values (97, 'GMC', 'Suburban 1500', 1998);
insert into automoviles (id, marca, modelo, anio_modelo) values (98, 'Chevrolet', 'Tahoe', 1995);
insert into automoviles (id, marca, modelo, anio_modelo) values (99, 'Pontiac', 'GTO', 2004);
insert into automoviles (id, marca, modelo, anio_modelo) values (100, 'Chevrolet', 'Corvette', 1968);
insert into automoviles (id, marca, modelo, anio_modelo) values (101, 'Hyundai', 'Tucson', 2012);
insert into automoviles (id, marca, modelo, anio_modelo) values (102, 'Nissan', 'Pathfinder', 1995);
insert into automoviles (id, marca, modelo, anio_modelo) values (103, 'Chevrolet', 'Express', 2007);
insert into automoviles (id, marca, modelo, anio_modelo) values (104, 'Isuzu', 'Oasis', 1996);
insert into automoviles (id, marca, modelo, anio_modelo) values (105, 'Pontiac', 'Montana', 2003);
insert into automoviles (id, marca, modelo, anio_modelo) values (106, 'Ford', 'LTD Crown Victoria', 1985);
insert into automoviles (id, marca, modelo, anio_modelo) values (107, 'BMW', 'X6', 2008);
insert into automoviles (id, marca, modelo, anio_modelo) values (108, 'Chevrolet', 'S10', 2003);
insert into automoviles (id, marca, modelo, anio_modelo) values (109, 'Ford', 'E150', 1984);
insert into automoviles (id, marca, modelo, anio_modelo) values (110, 'Jeep', 'Wrangler', 1992);
insert into automoviles (id, marca, modelo, anio_modelo) values (111, 'BMW', 'Z4', 2003);
insert into automoviles (id, marca, modelo, anio_modelo) values (112, 'Plymouth', 'Reliant', 1981);
insert into automoviles (id, marca, modelo, anio_modelo) values (113, 'Ford', 'Ranger', 1997);
insert into automoviles (id, marca, modelo, anio_modelo) values (114, 'Dodge', 'Ram Van 1500', 2003);
insert into automoviles (id, marca, modelo, anio_modelo) values (115, 'Pontiac', 'Bonneville', 2005);
insert into automoviles (id, marca, modelo, anio_modelo) values (116, 'Ford', 'Expedition', 2004);
insert into automoviles (id, marca, modelo, anio_modelo) values (117, 'Chevrolet', 'Lumina', 1998);
insert into automoviles (id, marca, modelo, anio_modelo) values (118, 'Dodge', 'Ram Van 3500', 1995);
insert into automoviles (id, marca, modelo, anio_modelo) values (119, 'Pontiac', 'Trans Sport', 1996);
insert into automoviles (id, marca, modelo, anio_modelo) values (120, 'Saturn', 'VUE', 2006);
insert into automoviles (id, marca, modelo, anio_modelo) values (121, 'GMC', 'Envoy', 2006);
insert into automoviles (id, marca, modelo, anio_modelo) values (122, 'Nissan', 'Murano', 2004);
insert into automoviles (id, marca, modelo, anio_modelo) values (123, 'Toyota', 'MR2', 1992);
insert into automoviles (id, marca, modelo, anio_modelo) values (124, 'Chevrolet', 'Suburban 2500', 2009);
insert into automoviles (id, marca, modelo, anio_modelo) values (125, 'Lincoln', 'Town Car', 1984);
insert into automoviles (id, marca, modelo, anio_modelo) values (126, 'Dodge', 'Dynasty', 1993);
insert into automoviles (id, marca, modelo, anio_modelo) values (127, 'Honda', 'FCX Clarity', 2012);
insert into automoviles (id, marca, modelo, anio_modelo) values (128, 'Toyota', 'Avalon', 2009);
insert into automoviles (id, marca, modelo, anio_modelo) values (129, 'Land Rover', 'Range Rover', 2009);
insert into automoviles (id, marca, modelo, anio_modelo) values (130, 'Jaguar', 'XJ', 2011);
insert into automoviles (id, marca, modelo, anio_modelo) values (131, 'Hyundai', 'Genesis', 2009);
insert into automoviles (id, marca, modelo, anio_modelo) values (132, 'Chevrolet', 'Corvette', 1967);
insert into automoviles (id, marca, modelo, anio_modelo) values (133, 'Ford', 'Tempo', 1985);
insert into automoviles (id, marca, modelo, anio_modelo) values (134, 'Lexus', 'GS', 2001);
insert into automoviles (id, marca, modelo, anio_modelo) values (135, 'Subaru', 'Impreza', 1996);
insert into automoviles (id, marca, modelo, anio_modelo) values (136, 'Chevrolet', 'Sportvan G30', 1993);
insert into automoviles (id, marca, modelo, anio_modelo) values (137, 'Hyundai', 'Tiburon', 2008);
insert into automoviles (id, marca, modelo, anio_modelo) values (138, 'Land Rover', 'Discovery Series II', 2001);
insert into automoviles (id, marca, modelo, anio_modelo) values (139, 'Hyundai', 'Elantra', 2000);
insert into automoviles (id, marca, modelo, anio_modelo) values (140, 'Jaguar', 'XJ Series', 2002);
insert into automoviles (id, marca, modelo, anio_modelo) values (141, 'Chevrolet', 'Uplander', 2006);
insert into automoviles (id, marca, modelo, anio_modelo) values (142, 'Honda', 'Civic', 2001);
insert into automoviles (id, marca, modelo, anio_modelo) values (143, 'Nissan', 'GT-R', 2011);
insert into automoviles (id, marca, modelo, anio_modelo) values (144, 'Rolls-Royce', 'Phantom', 2010);
insert into automoviles (id, marca, modelo, anio_modelo) values (145, 'Suzuki', 'XL-7', 2003);
insert into automoviles (id, marca, modelo, anio_modelo) values (146, 'Infiniti', 'G35', 2007);
insert into automoviles (id, marca, modelo, anio_modelo) values (147, 'Pontiac', 'Grand Prix', 1966);
insert into automoviles (id, marca, modelo, anio_modelo) values (148, 'Toyota', 'Avalon', 2004);
insert into automoviles (id, marca, modelo, anio_modelo) values (149, 'Nissan', 'Versa', 2012);
insert into automoviles (id, marca, modelo, anio_modelo) values (150, 'Pontiac', 'Sunbird', 1990);
insert into automoviles (id, marca, modelo, anio_modelo) values (151, 'Mazda', 'GLC', 1984);
insert into automoviles (id, marca, modelo, anio_modelo) values (152, 'Ford', 'Focus', 2002);
insert into automoviles (id, marca, modelo, anio_modelo) values (153, 'MINI', 'Cooper Countryman', 2012);
insert into automoviles (id, marca, modelo, anio_modelo) values (154, 'Pontiac', 'Grand Prix', 2006);
insert into automoviles (id, marca, modelo, anio_modelo) values (155, 'Mercedes-Benz', 'S-Class', 1997);
insert into automoviles (id, marca, modelo, anio_modelo) values (156, 'Ford', 'Focus', 2002);
insert into automoviles (id, marca, modelo, anio_modelo) values (157, 'Lexus', 'LS Hybrid', 2010);
insert into automoviles (id, marca, modelo, anio_modelo) values (158, 'Ford', 'Taurus', 1998);
insert into automoviles (id, marca, modelo, anio_modelo) values (159, 'Pontiac', 'Daewoo Kalos', 2006);
insert into automoviles (id, marca, modelo, anio_modelo) values (160, 'Ford', 'Contour', 2000);
insert into automoviles (id, marca, modelo, anio_modelo) values (161, 'Chevrolet', 'Express 1500', 1999);
insert into automoviles (id, marca, modelo, anio_modelo) values (162, 'GMC', '2500 Club Coupe', 1993);
insert into automoviles (id, marca, modelo, anio_modelo) values (163, 'Ford', 'E-Series', 1987);
insert into automoviles (id, marca, modelo, anio_modelo) values (164, 'Buick', 'Regal', 1994);
insert into automoviles (id, marca, modelo, anio_modelo) values (165, 'Hyundai', 'Sonata', 2010);
insert into automoviles (id, marca, modelo, anio_modelo) values (166, 'Oldsmobile', '98', 1996);
insert into automoviles (id, marca, modelo, anio_modelo) values (167, 'Mazda', '323', 1992);
insert into automoviles (id, marca, modelo, anio_modelo) values (168, 'Mercedes-Benz', 'Sprinter 2500', 2011);
insert into automoviles (id, marca, modelo, anio_modelo) values (169, 'Jeep', 'Wrangler', 2000);
insert into automoviles (id, marca, modelo, anio_modelo) values (170, 'GMC', 'Suburban 2500', 1996);
insert into automoviles (id, marca, modelo, anio_modelo) values (171, 'Audi', '80/90', 1988);
insert into automoviles (id, marca, modelo, anio_modelo) values (172, 'Subaru', 'Alcyone SVX', 1994);
insert into automoviles (id, marca, modelo, anio_modelo) values (173, 'Chevrolet', 'Suburban 1500', 2005);
insert into automoviles (id, marca, modelo, anio_modelo) values (174, 'Toyota', '4Runner', 2009);
insert into automoviles (id, marca, modelo, anio_modelo) values (175, 'Mazda', 'Mazda3', 2012);
insert into automoviles (id, marca, modelo, anio_modelo) values (176, 'Mitsubishi', 'Pajero', 1989);
insert into automoviles (id, marca, modelo, anio_modelo) values (177, 'Pontiac', 'LeMans', 1992);
insert into automoviles (id, marca, modelo, anio_modelo) values (178, 'Volkswagen', 'Fox', 1990);
insert into automoviles (id, marca, modelo, anio_modelo) values (179, 'Chevrolet', 'Monte Carlo', 2000);
insert into automoviles (id, marca, modelo, anio_modelo) values (180, 'GMC', '1500 Club Coupe', 1999);
insert into automoviles (id, marca, modelo, anio_modelo) values (181, 'Mercury', 'Lynx', 1986);
insert into automoviles (id, marca, modelo, anio_modelo) values (182, 'Ford', 'Escort', 1999);
insert into automoviles (id, marca, modelo, anio_modelo) values (183, 'Saturn', 'Sky', 2008);
insert into automoviles (id, marca, modelo, anio_modelo) values (184, 'Toyota', 'T100 Xtra', 1997);
insert into automoviles (id, marca, modelo, anio_modelo) values (185, 'Toyota', 'Tacoma Xtra', 2002);
insert into automoviles (id, marca, modelo, anio_modelo) values (186, 'Chevrolet', 'Suburban 2500', 2007);
insert into automoviles (id, marca, modelo, anio_modelo) values (187, 'Mazda', 'B-Series', 2000);
insert into automoviles (id, marca, modelo, anio_modelo) values (188, 'Toyota', 'Camry', 2006);
insert into automoviles (id, marca, modelo, anio_modelo) values (189, 'Saturn', 'L-Series', 2004);
insert into automoviles (id, marca, modelo, anio_modelo) values (190, 'Hyundai', 'Tucson', 2010);
insert into automoviles (id, marca, modelo, anio_modelo) values (191, 'Ford', 'Torino', 1970);
insert into automoviles (id, marca, modelo, anio_modelo) values (192, 'Dodge', 'Ram 1500 Club', 1995);
insert into automoviles (id, marca, modelo, anio_modelo) values (193, 'Jeep', 'Compass', 2010);
insert into automoviles (id, marca, modelo, anio_modelo) values (194, 'Buick', 'Roadmaster', 1991);
insert into automoviles (id, marca, modelo, anio_modelo) values (195, 'Toyota', 'Supra', 1996);
insert into automoviles (id, marca, modelo, anio_modelo) values (196, 'Maserati', 'GranTurismo', 2010);
insert into automoviles (id, marca, modelo, anio_modelo) values (197, 'Acura', 'TL', 2001);
insert into automoviles (id, marca, modelo, anio_modelo) values (198, 'Ford', 'Excursion', 2000);
insert into automoviles (id, marca, modelo, anio_modelo) values (199, 'Suzuki', 'Daewoo Magnus', 2006);
insert into automoviles (id, marca, modelo, anio_modelo) values (200, 'Lexus', 'ES', 1997);
insert into automoviles (id, marca, modelo, anio_modelo) values (201, 'Jensen', 'Interceptor', 1967);
insert into automoviles (id, marca, modelo, anio_modelo) values (202, 'Hyundai', 'Elantra', 2012);
insert into automoviles (id, marca, modelo, anio_modelo) values (203, 'Volvo', 'S80', 2004);
insert into automoviles (id, marca, modelo, anio_modelo) values (204, 'GMC', 'Savana 2500', 2010);
insert into automoviles (id, marca, modelo, anio_modelo) values (205, 'Suzuki', 'SJ', 1985);
insert into automoviles (id, marca, modelo, anio_modelo) values (206, 'Volvo', 'C70', 2007);
insert into automoviles (id, marca, modelo, anio_modelo) values (207, 'Ford', 'F150', 2005);
insert into automoviles (id, marca, modelo, anio_modelo) values (208, 'Audi', 'A8', 2002);
insert into automoviles (id, marca, modelo, anio_modelo) values (209, 'Chrysler', 'Town & Country', 1994);
insert into automoviles (id, marca, modelo, anio_modelo) values (210, 'Volkswagen', 'Eurovan', 1995);
insert into automoviles (id, marca, modelo, anio_modelo) values (211, 'Pontiac', 'Sunbird', 1990);
insert into automoviles (id, marca, modelo, anio_modelo) values (212, 'Jeep', 'Wrangler', 1994);
insert into automoviles (id, marca, modelo, anio_modelo) values (213, 'Ford', 'Five Hundred', 2006);
insert into automoviles (id, marca, modelo, anio_modelo) values (214, 'Nissan', 'Altima', 2012);
insert into automoviles (id, marca, modelo, anio_modelo) values (215, 'Cadillac', 'DTS', 2006);
insert into automoviles (id, marca, modelo, anio_modelo) values (216, 'Chevrolet', 'S10', 1993);
insert into automoviles (id, marca, modelo, anio_modelo) values (217, 'Honda', 'CR-V', 2012);
insert into automoviles (id, marca, modelo, anio_modelo) values (218, 'Toyota', 'Avalon', 2007);
insert into automoviles (id, marca, modelo, anio_modelo) values (219, 'Chevrolet', 'Express 1500', 2005);
insert into automoviles (id, marca, modelo, anio_modelo) values (220, 'Mercedes-Benz', '300E', 1993);
insert into automoviles (id, marca, modelo, anio_modelo) values (221, 'Mazda', 'Familia', 1992);
insert into automoviles (id, marca, modelo, anio_modelo) values (222, 'Buick', 'LaCrosse', 2011);
insert into automoviles (id, marca, modelo, anio_modelo) values (223, 'Spyker', 'C8 Spyder Wide Body', 2004);
insert into automoviles (id, marca, modelo, anio_modelo) values (224, 'Ford', 'Taurus', 1994);
insert into automoviles (id, marca, modelo, anio_modelo) values (225, 'Ford', 'Transit Connect', 2010);
insert into automoviles (id, marca, modelo, anio_modelo) values (226, 'Mitsubishi', 'Lancer', 2011);
insert into automoviles (id, marca, modelo, anio_modelo) values (227, 'Ford', 'Thunderbird', 2003);
insert into automoviles (id, marca, modelo, anio_modelo) values (228, 'Dodge', 'Caravan', 1993);
insert into automoviles (id, marca, modelo, anio_modelo) values (229, 'Volkswagen', 'New Beetle', 2009);
insert into automoviles (id, marca, modelo, anio_modelo) values (230, 'BMW', 'Z8', 2002);
insert into automoviles (id, marca, modelo, anio_modelo) values (231, 'Maserati', 'Karif', 1990);
insert into automoviles (id, marca, modelo, anio_modelo) values (232, 'Chrysler', 'New Yorker', 1995);
insert into automoviles (id, marca, modelo, anio_modelo) values (233, 'Audi', '5000S', 1985);
insert into automoviles (id, marca, modelo, anio_modelo) values (234, 'Buick', 'Regal', 1997);
insert into automoviles (id, marca, modelo, anio_modelo) values (235, 'Saab', '9-5', 2000);
insert into automoviles (id, marca, modelo, anio_modelo) values (236, 'Infiniti', 'Q', 1996);
insert into automoviles (id, marca, modelo, anio_modelo) values (237, 'Toyota', 'Sienna', 2005);
insert into automoviles (id, marca, modelo, anio_modelo) values (238, 'Buick', 'Century', 1986);
insert into automoviles (id, marca, modelo, anio_modelo) values (239, 'Dodge', 'D350', 1992);
insert into automoviles (id, marca, modelo, anio_modelo) values (240, 'Hyundai', 'Sonata', 2006);
insert into automoviles (id, marca, modelo, anio_modelo) values (241, 'Kia', 'Spectra', 2009);
insert into automoviles (id, marca, modelo, anio_modelo) values (242, 'Volvo', 'V50', 2010);
insert into automoviles (id, marca, modelo, anio_modelo) values (243, 'Ford', 'LTD Crown Victoria', 1987);
insert into automoviles (id, marca, modelo, anio_modelo) values (244, 'Toyota', 'Tacoma', 2008);
insert into automoviles (id, marca, modelo, anio_modelo) values (245, 'Maserati', 'Quattroporte', 2007);
insert into automoviles (id, marca, modelo, anio_modelo) values (246, 'Mitsubishi', 'Lancer', 2010);
insert into automoviles (id, marca, modelo, anio_modelo) values (247, 'Lexus', 'LX', 1998);
insert into automoviles (id, marca, modelo, anio_modelo) values (248, 'Pontiac', 'Firebird', 1999);
insert into automoviles (id, marca, modelo, anio_modelo) values (249, 'Lexus', 'LX', 1998);
insert into automoviles (id, marca, modelo, anio_modelo) values (250, 'Honda', 'Odyssey', 2000);
insert into automoviles (id, marca, modelo, anio_modelo) values (251, 'Hyundai', 'Tucson', 2009);
insert into automoviles (id, marca, modelo, anio_modelo) values (252, 'Infiniti', 'Q', 1994);
insert into automoviles (id, marca, modelo, anio_modelo) values (253, 'Toyota', 'Tundra', 2010);
insert into automoviles (id, marca, modelo, anio_modelo) values (254, 'Volvo', 'XC70', 2009);
insert into automoviles (id, marca, modelo, anio_modelo) values (255, 'Toyota', 'Tercel', 1997);
insert into automoviles (id, marca, modelo, anio_modelo) values (256, 'Audi', 'A4', 1999);
insert into automoviles (id, marca, modelo, anio_modelo) values (257, 'GMC', 'Sierra 3500', 2002);
insert into automoviles (id, marca, modelo, anio_modelo) values (258, 'Ford', 'F250', 1997);
insert into automoviles (id, marca, modelo, anio_modelo) values (259, 'Dodge', 'Stratus', 2006);
insert into automoviles (id, marca, modelo, anio_modelo) values (260, 'Mazda', 'Mazda5', 2006);
insert into automoviles (id, marca, modelo, anio_modelo) values (261, 'Suzuki', 'Vitara', 1999);
insert into automoviles (id, marca, modelo, anio_modelo) values (262, 'Jaguar', 'S-Type', 2000);
insert into automoviles (id, marca, modelo, anio_modelo) values (263, 'Chevrolet', 'Silverado 2500', 2004);
insert into automoviles (id, marca, modelo, anio_modelo) values (264, 'GMC', 'Rally Wagon 2500', 1992);
insert into automoviles (id, marca, modelo, anio_modelo) values (265, 'Cadillac', 'STS', 2009);
insert into automoviles (id, marca, modelo, anio_modelo) values (266, 'Maserati', 'Spyder', 2002);
insert into automoviles (id, marca, modelo, anio_modelo) values (267, 'Ford', 'Crown Victoria', 2003);
insert into automoviles (id, marca, modelo, anio_modelo) values (268, 'Mazda', 'B-Series', 2005);
insert into automoviles (id, marca, modelo, anio_modelo) values (269, 'Buick', 'Riviera', 1988);
insert into automoviles (id, marca, modelo, anio_modelo) values (270, 'Ford', 'Thunderbird', 1992);
insert into automoviles (id, marca, modelo, anio_modelo) values (271, 'Ford', 'E350', 2010);
insert into automoviles (id, marca, modelo, anio_modelo) values (272, 'Maybach', '62', 2008);
insert into automoviles (id, marca, modelo, anio_modelo) values (273, 'Subaru', 'Impreza', 2007);
insert into automoviles (id, marca, modelo, anio_modelo) values (274, 'Hyundai', 'Genesis Coupe', 2010);
insert into automoviles (id, marca, modelo, anio_modelo) values (275, 'MINI', 'Clubman', 2009);
insert into automoviles (id, marca, modelo, anio_modelo) values (276, 'Mazda', 'MPV', 1989);
insert into automoviles (id, marca, modelo, anio_modelo) values (277, 'Plymouth', 'Laser', 1992);
insert into automoviles (id, marca, modelo, anio_modelo) values (278, 'Mitsubishi', 'Galant', 1990);
insert into automoviles (id, marca, modelo, anio_modelo) values (279, 'Chevrolet', 'Uplander', 2006);
insert into automoviles (id, marca, modelo, anio_modelo) values (280, 'Mazda', 'Mazdaspeed 3', 2009);
insert into automoviles (id, marca, modelo, anio_modelo) values (281, 'Volvo', 'S60', 2011);
insert into automoviles (id, marca, modelo, anio_modelo) values (282, 'Ford', 'Probe', 1992);
insert into automoviles (id, marca, modelo, anio_modelo) values (283, 'Maserati', 'Gran Sport', 2006);
insert into automoviles (id, marca, modelo, anio_modelo) values (284, 'Rolls-Royce', 'Ghost', 2012);
insert into automoviles (id, marca, modelo, anio_modelo) values (285, 'Chevrolet', 'Avalanche', 2007);
insert into automoviles (id, marca, modelo, anio_modelo) values (286, 'Suzuki', 'Cultus', 1985);
insert into automoviles (id, marca, modelo, anio_modelo) values (287, 'Isuzu', 'VehiCROSS', 2001);
insert into automoviles (id, marca, modelo, anio_modelo) values (288, 'Pontiac', 'Sunbird', 1991);
insert into automoviles (id, marca, modelo, anio_modelo) values (289, 'Subaru', 'Outback', 2006);
insert into automoviles (id, marca, modelo, anio_modelo) values (290, 'Mercedes-Benz', 'C-Class', 2011);
insert into automoviles (id, marca, modelo, anio_modelo) values (291, 'Chevrolet', 'Corvette', 1993);
insert into automoviles (id, marca, modelo, anio_modelo) values (292, 'Plymouth', 'Prowler', 1999);
insert into automoviles (id, marca, modelo, anio_modelo) values (293, 'Nissan', '240SX', 1994);
insert into automoviles (id, marca, modelo, anio_modelo) values (294, 'Mercedes-Benz', 'SL-Class', 2005);
insert into automoviles (id, marca, modelo, anio_modelo) values (295, 'Volvo', 'V70', 2002);
insert into automoviles (id, marca, modelo, anio_modelo) values (296, 'Toyota', 'Sienna', 2012);
insert into automoviles (id, marca, modelo, anio_modelo) values (297, 'Maserati', 'Quattroporte', 2011);
insert into automoviles (id, marca, modelo, anio_modelo) values (298, 'Infiniti', 'G', 2001);
insert into automoviles (id, marca, modelo, anio_modelo) values (299, 'Mitsubishi', 'Montero Sport', 2002);
insert into automoviles (id, marca, modelo, anio_modelo) values (300, 'Ford', 'F450', 2011);
